[package]
name = "vtubestudio"
version = "0.1.0-alpha.0"
edition = "2018"

[dependencies]
futures-core = "0.3.17"
futures-sink = "0.3.17"
futures-util = "0.3.17"
paste = "1.0.5"
pin-project-lite = "0.2.7"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["sync"] }
tokio-tower = "0.6.0"
tokio-tungstenite = "0.15.0"
tower = { version = "0.4.10", features = ["util"] }

[dev-dependencies]
tokio = { version = "1.13.0", features = ["macros"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.6.9", features = ["codec"] }
tower = { version = "0.4.10", features = ["reconnect"] }
tower-test = "0.4.0"
