name: CI
on: [pull_request]

jobs:

  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --all-features --verbose
    - run: cargo test --no-default-features --verbose
    - name: Check for uncommitted changes
      shell: bash
      run: |
        if [[ ! -z $(git status --short) ]]; then
          echo "Found uncommitted changes after running tests." && exit 1
        fi

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: "rustfmt"
    - run: rustup component add rustfmt
    - uses: Swatinem/rust-cache@v2
    - run: cargo fmt --all -- --check

